services:
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    volumes:
      - redis-data:/data
    networks:
      - across_relayer_network
    restart: always
    command: redis-server
    healthcheck:
      test: redis-cli ping
      interval: 15s
      timeout: 5s
      retries: 3

  relayer_1:
    container_name: relayer_1
    image: ${AWS_ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${ACROSS_RELAYER_IMAGE_TAG}
    platform: linux/amd64
    depends_on:
      redis:
        condition: service_healthy
      fluent-bit:
        condition: service_healthy
    networks:
      - across_relayer_network
    restart: always
    command: ["/bin/sh", "/home/lisk/across-relayer/scripts/${NETWORK:-mainnet}/containerStart_relayer_1.sh"]
    logging:
      driver: fluentd
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - ${RELAYER_1_API_SERVER_HOST:-0.0.0.0}:${RELAYER_1_API_SERVER_PORT:-3000}:${RELAYER_1_API_SERVER_PORT:-3000}
    healthcheck:
      test: echo $$(wget --server-response http://relayer_1:${RELAYER_1_API_SERVER_PORT:-3000}/healthz 2>&1 | grep  '200 OK') | grep '200'  || exit 1

  rebalancer:
    container_name: rebalancer
    image: ${AWS_ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${ACROSS_RELAYER_IMAGE_TAG}
    platform: linux/amd64
    depends_on:
      redis:
        condition: service_healthy
      fluent-bit:
        condition: service_healthy
    networks:
      - across_relayer_network
    restart: always
    command: ["/bin/sh", "/home/lisk/across-relayer/scripts/${NETWORK:-mainnet}/containerStart_rebalancer.sh"]
    logging:
      driver: fluentd
    environment:
      - REDIS_URL=redis://redis:6379

  fluent-bit:
    image: amazon/aws-for-fluent-bit:2.32.2
    container_name: fluent-bit
    networks:
      - across_relayer_network
    volumes:
      - ./fluentbit_config:/fluent-bit/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2020/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  across_relayer_network:

volumes:
  redis-data:
